version: "3.8"

services: 
  nginx:
    image: nginx:alpine
    ports: 
      - "80:80"
    volumes: 
    #   - "./my.conf:/etc/nginx/conf.d/my.conf"
      - "./nginx.conf:/etc/nginx/nginx.conf"

  php:
    image: php:fpm
    ports: 
       - "9090-9092:9000"
    volumes: 
      - "./php:/potato/php"
      # - "./www.conf:/usr/local/etc/php-fpm.d/www.conf"